apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-gateway

resources:
  - cnpg-cluster.yaml
  - keycloak-deployment.yaml
  - keycloak-service.yaml
  - keycloak-ingress.yaml
